// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Stonk struct {
	ID int32
}

type User struct {
	ID           int32
	Name         string
	PasswordHash string
	Email        string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
